###
# @name loginPartner
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "mario@mario.com",
  "password": "secret"
}

###
@tokenPartner = {{ loginPartner.response.body.token }}


###
# @name loginCustomer
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "marioCustomer@mario.com",
  "password": "secret"
}

###
@tokenCustomer = {{ loginCustomer.response.body.token }}

###
POST http://localhost:3000/partners/register
Content-Type: application/json

{
  "name": "mario",
  "email": "mario@mario.com",
  "password": "secret",
  "company_name" : "company"
}

###
POST http://localhost:3000/customer/register
Content-Type: application/json

{
  "name": "marioCustomer",
  "email": "marioCustomer@mario.com",
  "password": "secret",
  "address" : "adress   ",
  "phone" : "123456789"
}

###
POST http://localhost:3000/partners/events
Content-Type: application/json
Authorization: Bearer {{ tokenPartner }}

{
  "name": "mario",
  "description": "descrição do evento",
  "date": "2021-09-09",
  "location" : "Localização do evento"
}

###
GET http://localhost:3000/partnes/events
Authorization: Bearer {{ tokenPartner }}

###
GET http://localhost:3000/partnes/events/1
Authorization: Bearer {{ tokenPartner }}

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/10